# Generated by Django 2.2.28 on 2023-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_froyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='froyt',
            name='nbghj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
